
$FullVersionToUse = "155.0.4264.0"

$Arguments = "--enable-features=MsW0I2,MsWShG,msBrowserAppsSupported,msBrowserExtensionsSupported,msBrowserFavoritesSupported,msBrowserNewTabSupported,msBrowserOmniboxSupported,msBrowserOptimizationGuideInternalsSupported,msBrowserResetPasswordSupported,msBrowserSidebarInternalsSupported,msBrowserSyncConfirmationSupported,msBrowserVersionSupported,msBrowserWdagInternalsSupported,msBrowserWebRtcLogsSupported,msComposeVoiceInputCopilotChat,msCopilotAdminSignal,msEdgeAffiliationLookup,msEdgeChangePasswordUrlAffiliationSource,msEdgeCopilotPulseLoggerFrameDetails,msEdgeCoworkAutofillAutoStuffKillSwitch,msEdgeJourneysShowIntentCards,msEdgeMarketingPagePrivateCopilotEligibility,msEdgeOnDeviceModelExecution,msEdgePerformanceDetector,msEdgeShoppingExperiencesGenericFlag0,msEdgeShoppingExperiencesGenericFlag1,msEdgeShoppingExperiencesGenericFlag2,msEdgeShoppingExperiencesGenericFlag3,msEdgeShoppingExperiencesGenericFlag4,msEdgeShoppingExperiencesGenericFlag5,msEdgeShoppingExperiencesGenericFlag6,msEdgeShoppingExperiencesGenericFlag7,msEdgeShoppingExperiencesGenericFlag8,msEdgeShoppingExperiencesGenericFlag9,msEdgeVerticalTabsConvergence,msIEModeWipPageInfoIntegration,msPerformanceInterventionActionableTabsTrigger,msPerformanceInterventionShadowBackend,msSSOBrowserHintPhase2,msSendVariationIdsHeaderFromAnyTopLevelOrigin,msSwapDiscard,msWebUIGsaInternals"

$content = @"
powershell.exe -WindowStyle hidden -Command "`$UserSID = [System.Security.Principal.WindowsIdentity]::GetCurrent().user.value;`$UserName = (Get-LocalUser | where-object -FilterScript {`$_.SID -eq `$UserSID}).name;Get-Process | where-object -FilterScript {`$_.path -eq \`"C:\Users\`$UserName\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe\`"} | ForEach-Object -Process {Stop-Process -Id `$_.id -Force -ErrorAction SilentlyContinue};& \`"C:\Users\`$UserName\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe\`" $Arguments"
"@

$content | Out-File -FilePath "C:\Users\$env:USERNAME\Downloads\EDGECAN Launcher $FullVersionToUse.bat"
